Rule to blacklist / prohibit certain file name patterns.
DukeLuo/eslint-plugin-check-file pull request #11
Opened 2022-10-27 11:48 UTC by florianehmke

This PR adds a new rule to prohibit certain file name patterns.

I think this is a good addition to this plugin. I often see inconsistent usage of file patterns like the ones used in the tests. Instead of documenting such things I want an eslint rule that takes care of that for me.

Let me know what you think and if I should change something.

2022-10-27 12:53 UTC, Biggisb approved these changes

2022-10-27 16:41 UTC, DukeLuo commented
@florianehmke Thanks for the new rule! It's a greate idea!

2022-10-30 14:19 UTC, DukeLuo requested changes

2022-10-31 10:10 UTC, DukeLuo approved these changes
It looks good!

2022-10-31 10:14 UTC, merged

2022-10-31 10:18 UTC, DukeLuo commented
@florianehmke  This PR is merged. This will be released over the weekend. Thanks!

2022-10-31 10:54 UTC, florianehmke commented
Thanks alot!

2022-11-05 14:15 UTC, DukeLuo commented
The PR has been released in version 1.3.0. Thanks!