fix: update filename-blocklist to check filename path
DukeLuo/eslint-plugin-check-file pull request #18
Opened 2023-03-21 20:32 UTC by jbkey23

While working with the `filename-blocklist` rule, I noticed my globs were not working properly when trying to pick files in specific folders. I then noticed that the rule was only checking the filename itself instead of the full path.

I made this update to check the full path instead of just the filename and added a few tests.

I also kept the rule message to just the filename so the message doesn't become too verbose with long paths.

I'm open to approaching this change differently, via a new rule option perhaps, as well if there is a desire not to introduce another breaking change to the rule.

Let me know your thoughts.

2023-03-22 15:18 UTC, DukeLuo requested changes
Yes, I noticed that these changes will introduce a breaking change. As I released a new major version just two weeks ago, it might be too early to release another major version.

To maintain backward compatibility, I suggest that we keep the existing behavior for all the v2 version and introduce the new behavior in the upcoming minor version. You can follow the example in this commit [https://github.com/DukeLuo/eslint-plugin-check-file/commit/c804992fcc05ebb1cb097970cba8881861e40382](https://github.com/DukeLuo/eslint-plugin-check-file/commit/c804992fcc05ebb1cb097970cba8881861e40382) as a guide.

2023-03-22 15:29 UTC, jbkey23 commented
> c804992

Cool, that makes sense. I can make that change 👍🏽

2023-03-23 13:19 UTC, DukeLuo approved these changes
Looks good to me.

2023-03-23 13:21 UTC, merged

2023-03-25 05:14 UTC, DukeLuo commented
This PR has been released.