feat: add support for nextjs private folders
DukeLuo/eslint-plugin-check-file pull request #31
Opened 2023-08-08 20:45 UTC by leepowellnbs

This PR adds support for Nexts colocation private folders https://nextjs.org/docs/app/building-your-application/routing/colocation#private-folders

2023-08-09 01:58 UTC, DukeLuo requested changes
Can you add a windows style test case in file `folder-naming-convention.windows.js`?

2023-08-09 06:36 UTC, leepowellnbs commented
> Can you add a windows style test case in file `folder-naming-convention.windows.js`?

Done

2023-08-09 12:03 UTC, DukeLuo requested changes

2023-08-09 12:07 UTC, leepowellnbs commented on tests/lib/rules/folder-naming-convention.windows.js
> +        options: [{ 'src/**/': 'NEXT_JS_APP_ROUTER_CASE' }],
My bad, missed that - should be resolved now.

2023-08-09 12:09 UTC, leepowellnbs commented
@DukeLuo Out of interest would you have any appetite to support the private folder style for files too? Next's documentation says:
```
While not a framework convention, you might also consider marking files outside private folders as "private" using the same underscore pattern.
```
So it would be good to support something like `_server-actions.ts` too. Happy to do that as a separate PR.

2023-08-09 13:35 UTC, DukeLuo approved these changes

2023-08-09 13:36 UTC, merged

2023-08-10 13:44 UTC, DukeLuo commented
> @DukeLuo Off the top of my head, the only two I can think of for filenames in a nextjs project would be kebab case and a private folder with kabab case. Can you think of any others?

Actually, i dont know a lot about nextjs. Based on what I know about nextjs so far, I think the answer is yes.

2023-08-13 15:01 UTC, DukeLuo commented
@leepowellnbs Thanks for your PR. This PR has been released in v2.6.2.